site_name: Tweet Classification for financial application
repo_url: https://github.com/AymSa/mlops-tweet-finance
nav:
  - Home: index.md
  - workflows:
    - main: src/main.md
  - src:
    - data: src/data.md
    - evaluate: src/evaluate.md
    - predict: src/predict.md
    - train: src/train.md
    - utils: src/utils.md
  - rest api:
    - api: app/api.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes
